updated pipeline, added PR comment for lighthouse tests

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -19,14 +19,28 @@ jobs:
                 node-version: 20
           - run: npm install
 
+          - uses: actions/checkout@master
+          - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
+          - name: Lighthouse
+            uses: foo-software/lighthouse-check-action@master
+            with:
+              outputDirectory: ${{ github.workspace }}/tmp/artifacts
+              gitHubAccessToken: ${{ secrets.GITHUB_APP_TOKEN }}
+              urls: 'https://yral.com/'
+          - name: Upload artifacts
+            uses: actions/upload-artifact@master
+            with:
+              name: Lighthouse reports
+              path: ${{ github.workspace }}/tmp/artifacts
+
           - name: Install Lighthouse
             run: npm install -g @lhci/cli@0.13.x
 
           - name: Run Lighthouse
-            # run: lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
-            run: lhci autorun 
-            # env: 
-            #     LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+            id: lhcitests
+            run: lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
+            env: 
+                LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_APP_TOKEN }}
 
           - name: install playwright
             run: npx playwright install    
@@ -35,11 +49,4 @@ jobs:
             id: tests
             # run: TESTPARAM=${{secrets.MAIL_PASSWORD}} npx playwright test --project=firefox
             run: npx playwright test --project=firefox
-
-          # - name: Check test result and comment
-          #   uses: peter-evans/create-or-update-comment@v1
-          #   with:
-          #     token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
-          #     issue-number: ${{ github.event.pull_request.number }}
-          #     body: |
-          #       ${{ steps.tests.outcome == '2 passed' && 'Test passed :heavy_check_mark:' || 'Test failed, Please check logs for details.' }}
+            continue-on-error: true
